server:
  port: 9999
spring:
  application:
    name: car-feign-wz
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true
