server:
  port: 9999
spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
  application:
    name: car-feign-wz
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000
