server:
    port: 8767

spring:
    application:
        name: springcloud-feign-NavTree


eureka:
    client:
        service-url:
            defalutZone: http://localhost:8761/eureka
feign:
    hystrix:
        enabled: true
