
server:
  port:  8768

spring:
  application:
    name: springcloud-feign
  main:
    allow-bean-definition-overriding: true
  mongodb:
    uri: localhost:27017/1809a


eureka:
  client:
    service-url:
      defalutZone: htto://localhost:8761/eureka

