server:
  port: 8766

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    pool:
    max-active: 20
    max-wait: -1
    max-idle: 8
    min-idle: 0
  application:
    name: springcloud-car-reg
  main:
    allow-bean-definition-overriding: true
  mongodb:
    uri: localhost:27017/1809a

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1809a06?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mybatis:
  mapper-locations: classpath:mapper/*xml

