mybatis:
  mapper-locations: classpath:dao/*.xml
server:
  port: 8888
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.157:3306/1809a06?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
  application:
    name: car-provider-wz
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

