mybatis:
  mapper-locations: classpath:dao/*.xml
server:
  port: 8888
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.128:3306/1809a06?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
  application:
    name: car-provider-wz
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 5000
    pool:
    min-idle: 0
    max-idle: 8
    max-wait: -1
    max-active: 20

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

